const KEY="spendly-expenses-v1", SETTINGS="spendly-settings-v1";let expenses=load(KEY,[]),settings=load(SETTINGS,{types:["Food","Travel","Shopping","Bills","Health","Subscriptions"],subs:["Groceries","Dining","Transport","Clothing","Recharge"],payments:["UPI","Cash","Debit Card","Credit Card","Net Banking"],banks:["SBI","HDFC","ICICI","Axis","Other"]}),charts={};
const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(n||0);
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}function save(){localStorage.setItem(KEY,JSON.stringify(expenses));localStorage.setItem(SETTINGS,JSON.stringify(settings))}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function today(){return new Date().toISOString().slice(0,10)} function dateObj(s){return new Date(s+"T00:00:00")} function monthOf(d){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")} function fmtDate(s){return dateObj(s).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}
function fillSelect(id,items,first=""){const el=$(id);el.innerHTML=first?'<option value="all">'+first+'</option>':"";items.forEach(x=>el.insertAdjacentHTML("beforeend",'<option value="'+esc(x)+'">'+esc(x)+"</option>"))}
function refreshSettings(){fillSelect("type",settings.types);fillSelect("subclass",settings.subs,"No sub-class");fillSelect("payment",settings.payments);fillSelect("bank",settings.banks);fillSelect("dashType",settings.types,"All types");fillSelect("expenseTypeFilter",settings.types,"All types");renderCategories()}
function openModal(id){$(id).classList.remove("hidden")}function closeModals(){document.querySelectorAll(".modal-backdrop").forEach(x=>x.classList.add("hidden"))}
function showView(view){document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));$(view+"View").classList.remove("hidden");document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("pageTitle").textContent={dashboard:"Dashboard",expenses:"Expenses",categories:"Categories"}[view]||"Dashboard";if(view==="expenses")renderExpenses()}
function selectedRows(){const period=$("periodFilter").value,type=$("dashType").value,q=$("dashSearch").value.toLowerCase().trim(),now=new Date(),thisM=monthOf(now),last=monthOf(new Date(now.getFullYear(),now.getMonth()-1,1));return expenses.filter(e=>(period==="all"||monthOf(dateObj(e.date))===(period==="month"?thisM:last))&&(type==="all"||e.type===type)&&(!q||(\`\${e.name} \${e.type} \${e.subclass} \${e.payment} \${e.bank} \${e.note}\`).toLowerCase().includes(q)))}
function renderDashboard(){const rows=selectedRows(),total=rows.reduce((a,e)=>a+e.amount,0),m=expenses.filter(e=>monthOf(dateObj(e.date))===monthOf(new Date())),mt=m.reduce((a,e)=>a+e.amount,0);$("totalStat").textContent=money(total);$("totalSub").textContent=rows.length+" transaction"+(rows.length===1?"":"s");$("monthStat").textContent=money(mt);$("monthSub").textContent=m.length+" transaction"+(m.length===1?"":"s");$("avgStat").textContent=money(rows.length?total/rows.length:0);const groups={};rows.forEach(e=>groups[e.type]=(groups[e.type]||0)+e.amount);const top=Object.entries(groups).sort((a,b)=>b[1]-a[1])[0];$("topStat").textContent=top?top[0]:"—";$("topSub").textContent=top?money(top[1]):"No expenses yet";renderCharts(rows);renderRecent(rows)}
function renderCharts(rows){Object.values(charts).forEach(c=>c?.destroy());const daily={},cats={};rows.forEach(e=>{daily[e.date]=(daily[e.date]||0)+e.amount;cats[e.type]=(cats[e.type]||0)+e.amount});const days=Object.keys(daily).sort(),pairs=Object.entries(cats).sort((a,b)=>b[1]-a[1]),opts={responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:"#aeb8cc",font:{size:10}}},tooltip:{callbacks:{label:c=>" "+money(c.raw)}}},scales:{x:{ticks:{color:"#77849d"},grid:{color:"#1c2537"}},y:{ticks:{color:"#77849d",callback:v=>money(v)},grid:{color:"#1c2537"}}}};charts.trend=new Chart($("trendChart"),{type:"line",data:{labels:days.map(fmtDate),datasets:[{data:days.map(d=>daily[d]),borderColor:"#9b8cff",backgroundColor:"rgba(155,140,255,.12)",fill:true,tension:.3,pointRadius:3}]},options:{...opts,plugins:{legend:{display:false}}}});charts.type=new Chart($("typeChart"),{type:"doughnut",data:{labels:pairs.map(x=>x[0]),datasets:[{data:pairs.map(x=>x[1]),backgroundColor:["#9b8cff","#57dfb0","#5ddcff","#ff72b2","#ffc857","#ff7d67","#7c8cff"],borderWidth:2,borderColor:"#101625"}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"right",labels:{color:"#aeb8cc",boxWidth:11,font:{size:10}}}}}})}
function renderRecent(rows){const top=[...rows].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);$("recentList").innerHTML=top.length?top.map(e=>'<div class="recent-row"><div><div class="expense-name">'+esc(e.name)+'</div><div class="expense-meta">'+fmtDate(e.date)+" · "+esc(e.payment)+'</div></div><span class="badge">'+esc(e.type)+'</span><div class="amount">'+money(e.amount)+"</div></div>").join(""):'<div class="empty">No expenses yet. Add your first transaction.</div>'}
function renderExpenses(){const q=$("expenseSearch").value.toLowerCase().trim(),type=$("expenseTypeFilter").value,rows=expenses.filter(e=>(type==="all"||e.type===type)&&(!q||(\`\${e.name} \${e.type} \${e.subclass} \${e.payment} \${e.bank}\`).toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date));$("expenseCount").textContent=rows.length+" transaction"+(rows.length===1?"":"s");$("expenseTable").innerHTML=rows.length?rows.map(e=>'<tr><td>'+fmtDate(e.date)+'</td><td><strong>'+esc(e.name)+'</strong></td><td><span class="badge">'+esc(e.type)+'</span></td><td>'+esc(e.subclass||"—")+'</td><td>'+esc(e.payment)+'</td><td>'+esc(e.bank)+'</td><td class="right amount">'+money(e.amount)+'</td><td><button class="delete-btn" data-delete="'+e.id+'" title="Delete">×</button></td></tr>').join(""):'<tr><td colspan="8" class="empty">No matching expenses.</td></tr>'}
function renderCategories(){const totals={};expenses.forEach(e=>totals[e.type]=(totals[e.type]||0)+e.amount);$("categoryGrid").innerHTML=settings.types.map(t=>{const unique=[...new Set(expenses.filter(e=>e.type===t).map(e=>e.subclass).filter(Boolean))];return'<article class="card category-card"><h3>'+esc(t)+'</h3><p>'+money(totals[t]||0)+" spent · "+expenses.filter(e=>e.type===t).length+' transactions</p><div class="sub-list">'+(unique.length?unique:["No sub-classes used yet"]).map(s=>'<span class="sub">'+esc(s)+"</span>").join("")+"</div></article>"}).join("")||'<div class="empty">No categories yet.</div>'}
function addSimple(kind){$("simpleTitle").textContent=kind==="type"?"Add expense type":"Add sub-class";$("simpleLabel").textContent=kind==="type"?"Expense type":"Sub-class";$("simpleInput").value="";$("simpleForm").dataset.kind=kind;openModal("simpleModal");setTimeout(()=>$("simpleInput").focus(),50)}
$("simpleForm").addEventListener("submit",e=>{e.preventDefault();const kind=e.currentTarget.dataset.kind,v=$("simpleInput").value.trim();if(!v)return;const arr=kind==="type"?settings.types:settings.subs;if(!arr.some(x=>x.toLowerCase()===v.toLowerCase()))arr.push(v);save();refreshSettings();$(kind==="type"?"type":"subclass").value=v;closeModals()});
$("expenseForm").addEventListener("submit",e=>{e.preventDefault();const item={id:crypto.randomUUID(),date:$("date").value,name:$("name").value.trim(),type:$("type").value,subclass:$("subclass").value,payment:$("payment").value,bank:$("bank").value,amount:Number($("amount").value),note:$("note").value.trim()};if(!item.date||!item.name||!item.amount)return;expenses.push(item);save();e.currentTarget.reset();$("date").value=today();closeModals();renderAll()});
document.addEventListener("click",e=>{const nav=e.target.closest("[data-view]");if(nav)showView(nav.dataset.view);const link=e.target.closest("[data-view-link]");if(link)showView(link.dataset.viewLink);const del=e.target.closest("[data-delete]");if(del&&confirm("Delete this expense?")){expenses=expenses.filter(x=>x.id!==del.dataset.delete);save();renderAll()}if(e.target.matches("[data-close]")||e.target.classList.contains("modal-backdrop"))closeModals()});
$("addExpenseBtn").onclick=()=>{refreshSettings();$("date").value=today();openModal("expenseModal");$("name").focus()};$("addTypeBtn").onclick=()=>addSimple("type");$("addSubclassBtn").onclick=()=>addSimple("subclass");$("addCategoryBtn").onclick=()=>addSimple("type");
["periodFilter","dashType","dashSearch"].forEach(id=>$(id).addEventListener("input",renderDashboard));["expenseSearch","expenseTypeFilter"].forEach(id=>$(id).addEventListener("input",renderExpenses));
$("exportBtn").onclick=()=>{if(!expenses.length){alert("No expenses to export yet.");return}const head=["Date","Expense Name","Expense Type","Expense Sub Class","Amount (₹)","Payment MODE","BANK","Note"],rows=expenses.map(e=>[e.date,e.name,e.type,e.subclass,e.amount,e.payment,e.bank,e.note]),csv=[head,...rows].map(r=>r.map(v=>'"'+String(v??"").replace(/"/g,'""')+'"').join(",")).join("\\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="expenses.csv";a.click();URL.revokeObjectURL(a.href)};
function renderAll(){refreshSettings();renderDashboard();renderExpenses()}renderAll();$("date").value=today();