const DB_NAME="spendly-db", DB_VERSION=1, LEGACY_KEY="spendly-expenses-v1", LEGACY_SETTINGS="spendly-settings-v1";
let expenses=[],editingId=null,settings={types:["Food","Travel","Shopping","Bills","Health","Subscriptions"],subs:["Groceries","Dining","Transport","Clothing","Recharge"],payments:["UPI","Cash","Debit Card","Credit Card","Net Banking"],banks:["SBI","HDFC","ICICI","Axis","Other"]},charts={},dbPromise;

const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(n||0);

function openDB(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains("expenses"))db.createObjectStore("expenses",{keyPath:"id"});if(!db.objectStoreNames.contains("settings"))db.createObjectStore("settings",{keyPath:"key"})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});return dbPromise}
function idbGetAll(store){return openDB().then(db=>new Promise((resolve,reject)=>{const req=db.transaction(store,"readonly").objectStore(store).getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)}))}
function idbGet(store,key){return openDB().then(db=>new Promise((resolve,reject)=>{const req=db.transaction(store,"readonly").objectStore(store).get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)}))}
function idbPut(store,value){return openDB().then(db=>new Promise((resolve,reject)=>{const req=db.transaction(store,"readwrite").objectStore(store).put(value);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)}))}
function idbDelete(store,key){return openDB().then(db=>new Promise((resolve,reject)=>{const req=db.transaction(store,"readwrite").objectStore(store).delete(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)}))}
function legacyLoad(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
async function initDB(){try{expenses=await idbGetAll("expenses");const saved=await idbGet("settings","settings");if(saved?.value)settings=saved.value;const oldExpenses=legacyLoad(LEGACY_KEY,[]);const oldSettings=legacyLoad(LEGACY_SETTINGS,null);if(!expenses.length&&Array.isArray(oldExpenses)&&oldExpenses.length){for(const item of oldExpenses){item.date=normalizeDate(item.date);await idbPut("expenses",item)}expenses=oldExpenses}else{expenses=expenses.map(item=>({...item,date:normalizeDate(item.date)}))}if(!saved){if(oldSettings)settings=oldSettings;await idbPut("settings",{key:"settings",value:settings})}renderAll();$("date").value=today()}catch(err){console.error("IndexedDB unavailable:",err);expenses=legacyLoad(LEGACY_KEY,[]);settings=legacyLoad(LEGACY_SETTINGS,settings);renderAll();$("date").value=today();alert("Local database could not be opened. Your existing browser data is still available.")}}
async function persistExpense(item){await idbPut("expenses",item)}
async function persistSettings(){await idbPut("settings",{key:"settings",value:settings})}

function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function today(){const d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")} function normalizeDate(s){const v=String(s??"").trim();if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;const m=v.match(/^(\d{4}-\d{2}-\d{2})/);return m?m[1]:""} function dateObj(s){const v=normalizeDate(s);const [y,m,d]=v.split("-").map(Number);return v&&y&&m&&d?new Date(y,m-1,d):new Date(NaN)} function monthOf(d){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")} function fmtDate(s){const d=dateObj(s);return Number.isNaN(d.getTime())?"—":d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}
function fillSelect(id,items,first=""){const el=$(id);el.innerHTML=first?'<option value="all">'+first+"</option>":"";items.forEach(x=>el.insertAdjacentHTML("beforeend",'<option value="'+esc(x)+'">'+esc(x)+"</option>"))}
function refreshSettings(){fillSelect("type",settings.types);fillSelect("subclass",settings.subs,"No sub-class");fillSelect("payment",settings.payments);fillSelect("bank",settings.banks);fillSelect("dashType",settings.types,"All types");fillSelect("expenseTypeFilter",settings.types,"All types");renderCategories()}
function openModal(id){$(id).classList.remove("hidden")}function closeModals(){document.querySelectorAll(".modal-backdrop").forEach(x=>x.classList.add("hidden"));editingId=null}
function showView(view){document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));$(view+"View").classList.remove("hidden");document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("pageTitle").textContent={dashboard:"Dashboard",expenses:"Expenses",categories:"Categories"}[view]||"Dashboard";if(view==="expenses")renderExpenses()}
function selectedRows(){const period=$("periodFilter").value,type=$("dashType").value,q=$("dashSearch").value.toLowerCase().trim(),now=new Date(),thisM=monthOf(now),last=monthOf(new Date(now.getFullYear(),now.getMonth()-1,1));return expenses.filter(e=>(period==="all"||monthOf(dateObj(e.date))===(period==="month"?thisM:last))&&(type==="all"||e.type===type)&&(!q||(`${e.name} ${e.type} ${e.subclass} ${e.payment} ${e.bank} ${e.note}`).toLowerCase().includes(q)))}
function renderDashboard(){const rows=selectedRows(),total=rows.reduce((a,e)=>a+e.amount,0),m=expenses.filter(e=>monthOf(dateObj(e.date))===monthOf(new Date())),mt=m.reduce((a,e)=>a+e.amount,0);$("totalStat").textContent=money(total);$("totalSub").textContent=rows.length+" transaction"+(rows.length===1?"":"s");$("monthStat").textContent=money(mt);$("monthSub").textContent=m.length+" transaction"+(m.length===1?"":"s");$("avgStat").textContent=money(rows.length?total/rows.length:0);const groups={};rows.forEach(e=>groups[e.type]=(groups[e.type]||0)+e.amount);const top=Object.entries(groups).sort((a,b)=>b[1]-a[1])[0];$("topStat").textContent=top?top[0]:"—";$("topSub").textContent=top?money(top[1]):"No expenses yet";renderCharts(rows);renderRecent(rows)}
function renderCharts(rows){Object.values(charts).forEach(c=>c?.destroy());const daily={},cats={};rows.forEach(e=>{daily[e.date]=(daily[e.date]||0)+e.amount;cats[e.type]=(cats[e.type]||0)+e.amount});const days=Object.keys(daily).sort(),pairs=Object.entries(cats).sort((a,b)=>b[1]-a[1]),opts={responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:"#aeb8cc",font:{size:10}}},tooltip:{callbacks:{label:c=>" "+money(c.raw)}}},scales:{x:{ticks:{color:"#77849d"},grid:{color:"#1c2537"}},y:{ticks:{color:"#77849d",callback:v=>money(v)},grid:{color:"#1c2537"}}}};charts.trend=new Chart($("trendChart"),{type:"line",data:{labels:days.map(fmtDate),datasets:[{data:days.map(d=>daily[d]),borderColor:"#9b8cff",backgroundColor:"rgba(155,140,255,.12)",fill:true,tension:.3,pointRadius:3}]},options:{...opts,plugins:{legend:{display:false}}}});charts.type=new Chart($("typeChart"),{type:"doughnut",data:{labels:pairs.map(x=>x[0]),datasets:[{data:pairs.map(x=>x[1]),backgroundColor:["#9b8cff","#57dfb0","#5ddcff","#ff72b2","#ffc857","#ff7d67","#7c8cff"],borderWidth:2,borderColor:"#101625"}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"right",labels:{color:"#aeb8cc",boxWidth:11,font:{size:10}}}}}})}
function renderRecent(rows){const top=[...rows].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);$("recentList").innerHTML=top.length?top.map(e=>'<div class="recent-row"><div><div class="expense-name">'+esc(e.name)+'</div><div class="expense-meta">'+fmtDate(e.date)+" · "+esc(e.payment)+'</div></div><span class="badge">'+esc(e.type)+'</span><div class="amount">'+money(e.amount)+"</div></div>").join(""):'<div class="empty">No expenses yet. Add your first transaction.</div>'}
function editExpense(id){const item=expenses.find(x=>x.id===id);if(!item)return;editingId=id;refreshSettings();$("expenseModalEyebrow").textContent="EDIT TRANSACTION";$("expenseModalTitle").textContent="Edit expense";$("expenseSubmitBtn").textContent="Update expense";$("date").value=item.date;$("amount").value=item.amount;$("name").value=item.name;$("type").value=item.type;$("subclass").value=item.subclass||"";$("payment").value=item.payment||"";$("bank").value=item.bank||"";$("note").value=item.note||"";openModal("expenseModal");$("name").focus()}\nfunction resetExpenseModal(){editingId=null;$("expenseModalEyebrow").textContent="NEW TRANSACTION";$("expenseModalTitle").textContent="Add expense";$("expenseSubmitBtn").textContent="Save expense";$("expenseForm").reset();$("date").value=today()}\nfunction renderExpenses(){const q=$("expenseSearch").value.toLowerCase().trim(),type=$("expenseTypeFilter").value,rows=expenses.filter(e=>(type==="all"||e.type===type)&&(!q||(`${e.name} ${e.type} ${e.subclass} ${e.payment} ${e.bank}`).toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date));$("expenseCount").textContent=rows.length+" transaction"+(rows.length===1?"":"s");$("expenseTable").innerHTML=rows.length?rows.map(e=>'<tr><td>'+fmtDate(e.date)+'</td><td><strong>'+esc(e.name)+'</strong></td><td><span class="badge">'+esc(e.type)+'</span></td><td>'+esc(e.subclass||"—")+'</td><td>'+esc(e.payment)+'</td><td>'+esc(e.bank)+'</td><td class="right amount">'+money(e.amount)+'</td><td><button class="edit-btn" data-edit="'+e.id+'" title="Edit">✎</button><button class="delete-btn" data-delete="'+e.id+'" title="Delete">×</button></td></tr>').join(""):'<tr><td colspan="8" class="empty">No matching expenses.</td></tr>'}
function renderCategories(){const totals={};expenses.forEach(e=>totals[e.type]=(totals[e.type]||0)+e.amount);$("categoryGrid").innerHTML=settings.types.map(t=>{const unique=[...new Set(expenses.filter(e=>e.type===t).map(e=>e.subclass).filter(Boolean))];return'<article class="card category-card"><h3>'+esc(t)+'</h3><p>'+money(totals[t]||0)+" spent · "+expenses.filter(e=>e.type===t).length+' transactions</p><div class="sub-list">'+(unique.length?unique:["No sub-classes used yet"]).map(s=>'<span class="sub">'+esc(s)+"</span>").join("")+"</div></article>"}).join("")||'<div class="empty">No categories yet.</div>'}
function addSimple(kind){$("simpleTitle").textContent=kind==="type"?"Add expense type":"Add sub-class";$("simpleLabel").textContent=kind==="type"?"Expense type":"Sub-class";$("simpleInput").value="";$("simpleForm").dataset.kind=kind;openModal("simpleModal");setTimeout(()=>$("simpleInput").focus(),50)}

$("simpleForm").addEventListener("submit",async e=>{e.preventDefault();const kind=e.currentTarget.dataset.kind,v=$("simpleInput").value.trim();if(!v)return;const arr=kind==="type"?settings.types:settings.subs;if(!arr.some(x=>x.toLowerCase()===v.toLowerCase()))arr.push(v);await persistSettings();refreshSettings();$(kind==="type"?"type":"subclass").value=v;closeModals()});
$("expenseForm").addEventListener("submit",async e=>{e.preventDefault();const data={date:normalizeDate($("date").value),name:$("name").value.trim(),type:$("type").value,subclass:$("subclass").value,payment:$("payment").value,bank:$("bank").value,amount:Number($("amount").value),note:$("note").value.trim()};if(!data.date||!data.name||!Number.isFinite(data.amount)||data.amount<=0)return;if(editingId){const item={id:editingId,...data};await persistExpense(item);expenses=expenses.map(x=>x.id===editingId?item:x)}else{const item={id:crypto.randomUUID(),...data};await persistExpense(item);expenses.push(item)}e.currentTarget.reset();$("date").value=today();closeModals();resetExpenseModal();renderAll()});
document.addEventListener("click",async e=>{const nav=e.target.closest("[data-view]");if(nav)showView(nav.dataset.view);const link=e.target.closest("[data-view-link]");if(link)showView(link.dataset.viewLink);const edit=e.target.closest("[data-edit]");if(edit)editExpense(edit.dataset.edit);const del=e.target.closest("[data-delete]");if(del&&confirm("Delete this expense?")){await idbDelete("expenses",del.dataset.delete);expenses=expenses.filter(x=>x.id!==del.dataset.delete);renderAll()}if(e.target.matches("[data-close]")||e.target.classList.contains("modal-backdrop"))closeModals()});
$("addExpenseBtn").onclick=()=>{resetExpenseModal();refreshSettings();openModal("expenseModal");$("name").focus()};$("addTypeBtn").onclick=()=>addSimple("type");$("addSubclassBtn").onclick=()=>addSimple("subclass");$("addCategoryBtn").onclick=()=>addSimple("type");
["periodFilter","dashType","dashSearch"].forEach(id=>$(id).addEventListener("input",renderDashboard));["expenseSearch","expenseTypeFilter"].forEach(id=>$(id).addEventListener("input",renderExpenses));
$("exportBtn").onclick=()=>{if(!expenses.length){alert("No expenses to export yet.");return}const head=["Date","Expense Name","Expense Type","Expense Sub Class","Amount (₹)","Payment MODE","BANK","Note"],rows=expenses.map(e=>[e.date,e.name,e.type,e.subclass,e.amount,e.payment,e.bank,e.note]),csv=[head,...rows].map(r=>r.map(v=>'"'+String(v??"").replace(/"/g,'""')+'"').join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="expenses.csv";a.click();URL.revokeObjectURL(a.href)};
function renderAll(){refreshSettings();renderDashboard();renderExpenses()}initDB();